#!/usr/bin/env node
/**
 * mark_sold.js — Numismática Popper: sold-item lifecycle manager
 *
 * Usage:
 *   node mark_sold.js "search term"   → mark matching coin(s) as sold
 *   node mark_sold.js --purge         → remove sold items >7 days old + delete images
 *   node mark_sold.js --list-sold     → print all currently sold items
 *
 * Expects to be run from the project root (same directory as coins.json).
 */

const fs   = require('fs');
const path = require('path');
const os   = require('os');

const COINS_FILE   = path.join(__dirname, 'coins.json');
const LOG_FILE     = path.join(os.homedir(), 'Desktop', 'Popper', 'operational_log.md');
const SEVEN_DAYS   = 7 * 24 * 60 * 60 * 1000;

// ─── Helpers ─────────────────────────────────────────────────────────────────

function readCoins() {
  return JSON.parse(fs.readFileSync(COINS_FILE, 'utf8'));
}

function writeCoins(coins) {
  fs.writeFileSync(COINS_FILE, JSON.stringify(coins, null, 2), 'utf8');
}

function appendLog(entry) {
  const dir = path.dirname(LOG_FILE);
  if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });

  const timestamp = new Date().toISOString().replace('T', ' ').slice(0, 19);
  const block = `\n---\n\n### ${timestamp}\n\n${entry.trim()}\n`;

  if (!fs.existsSync(LOG_FILE)) {
    const header = '# Numismática Popper — Operational Log\n\n' +
      '_Auto-generated by mark_sold.js. Each entry documents a lifecycle action._\n';
    fs.writeFileSync(LOG_FILE, header + block, 'utf8');
  } else {
    fs.appendFileSync(LOG_FILE, block, 'utf8');
  }

  console.log(`\n📋 Log updated → ${LOG_FILE}`);
}

function normalize(str) {
  return String(str || '').toLowerCase().normalize('NFD').replace(/[̀-ͯ]/g, '');
}

// ─── Commands ────────────────────────────────────────────────────────────────

function markSold(searchTerm) {
  const coins   = readCoins();
  const term    = normalize(searchTerm);
  const matches = coins.filter(c =>
    normalize(c.title).includes(term) ||
    String(c.id) === searchTerm.trim()
  );

  if (matches.length === 0) {
    console.error(`✗ No coin found matching "${searchTerm}"`);
    process.exit(1);
  }

  const soldAt  = new Date().toISOString();
  const changed = [];

  matches.forEach(coin => {
    if (coin.status === 'sold') {
      console.log(`⚠  ID ${coin.id} "${coin.title}" is already marked sold — skipping`);
      return;
    }

    const cant = typeof coin.cantidad === 'number' ? coin.cantidad : 1;
    if (cant > 1) {
      coin.cantidad = cant - 1;
      changed.push({ coin, becameSold: false });
      console.log(`✓  Reduced stock for: [${coin.id}] ${coin.title} (remaining: ${coin.cantidad})`);
    } else {
      if (coin.hasOwnProperty('cantidad')) {
        coin.cantidad = 0;
      }
      coin.status = 'sold';
      coin.soldAt = soldAt;
      changed.push({ coin, becameSold: true });
      console.log(`✓  Marked as VENDIDO (Out of Stock): [${coin.id}] ${coin.title}`);
    }
  });

  if (changed.length === 0) process.exit(0);

  writeCoins(coins);

  const logEntry = [
    '**Action:** `mark_sold`',
    '',
    `**Query:** \`${searchTerm}\``,
    '',
    '**Items modified:**',
    ...changed.map(item => {
      const c = item.coin;
      if (item.becameSold) {
        return `- ID ${c.id}: _${c.title}_ (soldAt: ${soldAt} - OUT OF STOCK)`;
      } else {
        return `- ID ${c.id}: _${c.title}_ (Remaining stock: ${c.cantidad})`;
      }
    }),
    '',
    '**Visual effect:** grayscale overlay + VENDIDO ribbon applied on next page load for out of stock items.',
    '**Retention:** Out of stock items will remain visible for 7 days, then auto-purge.',
    '',
    '**Edge cases / notes:**',
    `- ${matches.length > changed.length ? `${matches.length - changed.length} match(es) already sold, skipped.` : 'No duplicates.'}`,
    '- Run `node mark_sold.js --purge` to clean up expired entries and their images.',
    '',
    '**Optimization suggestion:** If sold items accumulate, schedule `--purge` as a weekly cron.',
  ].join('\n');

  appendLog(logEntry);
}

function purgeExpired() {
  const coins    = readCoins();
  const now      = Date.now();
  const expired  = coins.filter(c =>
    c.status === 'sold' && c.soldAt &&
    (now - new Date(c.soldAt).getTime() > SEVEN_DAYS)
  );

  if (expired.length === 0) {
    console.log('✓ No expired sold items to purge.');
    return;
  }

  const deletedImages = [];
  expired.forEach(coin => {
    const images = Array.isArray(coin.images) ? coin.images : (coin.image ? [coin.image] : []);
    images.forEach(imgPath => {
      const abs = path.join(__dirname, imgPath);
      if (fs.existsSync(abs)) {
        fs.unlinkSync(abs);
        deletedImages.push(imgPath);
        console.log(`🗑  Deleted image: ${imgPath}`);
      }
    });
    console.log(`✗  Purged coin: [${coin.id}] ${coin.title}`);
  });

  const remaining = coins.filter(c => !expired.includes(c));
  writeCoins(remaining);

  console.log(`\n✓ Purged ${expired.length} coin(s), deleted ${deletedImages.length} image(s).`);

  const logEntry = [
    '**Action:** `purge_expired`',
    '',
    `**Items purged (${expired.length}):**`,
    ...expired.map(c => `- ID ${c.id}: _${c.title}_ (soldAt: ${c.soldAt})`),
    '',
    `**Images deleted (${deletedImages.length}):**`,
    ...(deletedImages.length ? deletedImages.map(p => `- \`${p}\``) : ['- None']),
    '',
    '**Edge cases / notes:**',
    `- Retention threshold: 7 days (${SEVEN_DAYS / 1000 / 3600}h).`,
    `- Remaining coins in catalog: ${remaining.length}.`,
    '',
    '**Optimization suggestion:** Automate with `crontab -e` → `0 3 * * 1 cd ~/path/to/project && node mark_sold.js --purge`',
  ].join('\n');

  appendLog(logEntry);
}

function listSold() {
  const coins = readCoins();
  const sold  = coins.filter(c => c.status === 'sold');
  if (sold.length === 0) { console.log('No sold items.'); return; }

  const now = Date.now();
  sold.forEach(c => {
    const soldAt   = new Date(c.soldAt);
    const elapsed  = now - soldAt.getTime();
    const daysLeft = Math.max(0, Math.ceil((SEVEN_DAYS - elapsed) / 86400000));
    const status   = elapsed > SEVEN_DAYS ? '⚠  EXPIRED (run --purge)' : `${daysLeft}d left`;
    console.log(`  [${c.id}] ${c.title}  —  sold ${soldAt.toLocaleDateString('es-AR')}  (${status})`);
  });
}

// ─── Entry point ─────────────────────────────────────────────────────────────

const [,, ...args] = process.argv;
const flag = args[0];

if (!flag || flag === '--help') {
  console.log([
    '',
    'Usage:',
    '  node mark_sold.js "search term"   Mark matching coin as sold',
    '  node mark_sold.js --purge         Remove expired sold items + delete images',
    '  node mark_sold.js --list-sold     Show current sold items with days remaining',
    '',
  ].join('\n'));
} else if (flag === '--purge') {
  purgeExpired();
} else if (flag === '--list-sold') {
  listSold();
} else {
  markSold(args.join(' '));
}
